"""empty message

Revision ID: 1c76ec0805b5
Revises: aee11463c361
Create Date: 2024-02-18 00:23:17.284345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c76ec0805b5'
down_revision: Union[str, None] = 'aee11463c361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'memo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('memo', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
