"""empty message

Revision ID: a1ddf3670a22
Revises: 67c2146874c2
Create Date: 2024-02-18 00:00:53.140898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ddf3670a22'
down_revision: Union[str, None] = '67c2146874c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('memo', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'memo')
    # ### end Alembic commands ###
