version: '3.7'
services:
  db:
    image: postgres:16
    container_name: lottery_db
    restart: always
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    image: lottery_image
    build:
      dockerfile: Dockerfile
      context: .
    container_name: lottery_app
    restart: always
    env_file:
      - .env-non-dev
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      sh -c "alembic upgrade head
      && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
      && python BOT/bot.py"
    ports:
      - 7777:8000


networks:
  default:
    name: hello_fastapi