version: '3.7'
services:
  db:
    image: postgres:16
    container_name: lottery_db
    restart: always
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"

  app:
    image: lottery_image
    build:
      context: .
    container_name: lottery_app
    restart: always
    env_file:
      - .env-non-dev
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      bash -c "alembic upgrade head && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
      && python BOT/bot.py"
    ports:
      - 7777:8000