version: '3.7'
services:
  db:
    image: postgres:16
    container_name: lottery_db
    restart: always
    env_file:
      - .env-non-dev
    environment:
      POSTGRES_DB: "lottery_app"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
#    user: '$UID:$GID'
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - postgres

  app:
    image: lottery_image
    build:
      context: .
    container_name: lottery_app
    restart: always
    env_file:
      - .env-non-dev
    depends_on:
      - db
    command: >
      bash -c "python BOT/bot.py && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    ports:
      - 7777:8000

volumes:
    data:
    pgadmin-data:
networks:
  postgres:
    driver: bridge